"""phone number voice settings

Revision ID: 24414f5bd46b
Revises: c89e73f71c6d
Create Date: 2026-09-26 08:20:40.452129
"""
from alembic import op
import sqlalchemy as sa


revision = '24414f5bd46b'
down_revision = 'c89e73f71c6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('voice_id', sa.String(length=64), server_default='', nullable=False))
    op.add_column('phone_numbers', sa.Column('voice_model', sa.String(length=40), server_default='eleven_multilingual_v2', nullable=False))
    op.add_column('phone_numbers', sa.Column('speaking_style', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'speaking_style')
    op.drop_column('phone_numbers', 'voice_model')
    op.drop_column('phone_numbers', 'voice_id')
    # ### end Alembic commands ###
