"""social posts extra flag

Revision ID: 2944b6976e59
Revises: 793d6de4d9bb
Create Date: 2026-10-09 18:09:44.198822
"""
from alembic import op
import sqlalchemy as sa


revision = '2944b6976e59'
down_revision = '793d6de4d9bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_posts', sa.Column('extra', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # one live *planned* post per platform and day — extra posts ordered by the operator sit outside the rule
    op.drop_index('uq_social_posts_platform_slot', table_name='social_posts')
    op.create_index('uq_social_posts_platform_slot', 'social_posts', ['platform', 'slot_date'], unique=True,
                    postgresql_where=sa.text("status not in ('cancelled','skipped') and not extra"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_social_posts_platform_slot', table_name='social_posts')
    op.create_index('uq_social_posts_platform_slot', 'social_posts', ['platform', 'slot_date'], unique=True,
                    postgresql_where=sa.text("status not in ('cancelled','skipped')"))
    op.drop_column('social_posts', 'extra')
    # ### end Alembic commands ###
