"""reception script

Revision ID: 299f641c5b3f
Revises: c9febc48ca3b
Create Date: 2026-09-26 21:20:26.830266
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '299f641c5b3f'
down_revision = 'c9febc48ca3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reception_scripts',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('persona_name', sa.String(length=60), nullable=False),
    sa.Column('address_form', sa.String(length=8), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=False),
    sa.Column('collect', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation', sa.Text(), nullable=False),
    sa.Column('avoid', sa.Text(), nullable=False),
    sa.Column('closing', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reception_scripts')
    # ### end Alembic commands ###
