"""ambassador programme

Revision ID: 3c1d29602dcc
Revises: 6abbbb75fde5
Create Date: 2026-09-30 20:13:14.726896
"""
import sqlalchemy as sa

from alembic import op

revision = '3c1d29602dcc'
down_revision = '6abbbb75fde5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambassadors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('cvr', sa.String(length=8), nullable=True),
    sa.Column('vat_registered', sa.Boolean(), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('motivation', sa.String(length=1000), nullable=False),
    sa.Column('cpr_enc', sa.LargeBinary(), nullable=True),
    sa.Column('bank_enc', sa.LargeBinary(), nullable=True),
    sa.Column('secrets_key_version', sa.String(length=32), nullable=True),
    sa.Column('bank_last4', sa.String(length=4), nullable=True),
    sa.Column('parent_name', sa.String(length=200), nullable=True),
    sa.Column('parent_email', sa.String(length=320), nullable=True),
    sa.Column('parent_token_hash', sa.String(length=64), nullable=True),
    sa.Column('parent_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rules_version', sa.String(length=40), nullable=False),
    sa.Column('rules_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bonus_minor', sa.BigInteger(), nullable=False),
    sa.Column('rate_bp', sa.Integer(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('private','company')", name='ck_ambassadors_kind'),
    sa.CheckConstraint("status in ('pending','active','suspended','rejected')", name='ck_ambassadors_status'),
    sa.CheckConstraint('bonus_minor >= 0', name='ck_ambassadors_bonus'),
    sa.CheckConstraint('months between 1 and 120', name='ck_ambassadors_months'),
    sa.CheckConstraint('rate_bp between 0 and 5000', name='ck_ambassadors_rate'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('parent_token_hash'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ambassador_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ambassador_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('income_type', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending','paid','cancelled')", name='ck_ambassador_payouts_status'),
    sa.ForeignKeyConstraint(['ambassador_id'], ['ambassadors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_ambassador_payouts_ambassador_id'), 'ambassador_payouts', ['ambassador_id'], unique=False)
    op.create_table('referral_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ambassador_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambassador_id'], ['ambassadors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ambassador_id', 'day', name='uq_referral_clicks_day')
    )
    op.create_table('referrals',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('ambassador_id', sa.UUID(), nullable=False),
    sa.Column('via', sa.String(length=8), nullable=False),
    sa.Column('first_paid_month', sa.Date(), nullable=True),
    sa.Column('attributed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("via in ('link','code','operator')", name='ck_referrals_via'),
    sa.ForeignKeyConstraint(['ambassador_id'], ['ambassadors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_referrals_ambassador_id'), 'referrals', ['ambassador_id'], unique=False)
    op.create_table('commission_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ambassador_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('base_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('hold_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payout_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('bonus','share','reversal')", name='ck_commission_entries_kind'),
    sa.CheckConstraint("status in ('held','payable','paid','reversed')", name='ck_commission_entries_status'),
    sa.ForeignKeyConstraint(['ambassador_id'], ['ambassadors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payout_id'], ['ambassador_payouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'kind', 'source_ref', name='uq_commission_entries_invoice_kind')
    )
    op.create_index('ix_commission_entries_ambassador_status', 'commission_entries', ['ambassador_id', 'status'], unique=False)
    op.create_index(op.f('ix_commission_entries_payout_id'), 'commission_entries', ['payout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commission_entries_payout_id'), table_name='commission_entries')
    op.drop_index('ix_commission_entries_ambassador_status', table_name='commission_entries')
    op.drop_table('commission_entries')
    op.drop_index(op.f('ix_referrals_ambassador_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('referral_clicks')
    op.drop_index(op.f('ix_ambassador_payouts_ambassador_id'), table_name='ambassador_payouts')
    op.drop_table('ambassador_payouts')
    op.drop_table('ambassadors')
    # ### end Alembic commands ###
