"""social account snapshots and post metrics

Revision ID: 3da6b0abc2dc
Revises: 6f6d583caceb
Create Date: 2026-10-08 14:39:06.340203
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3da6b0abc2dc'
down_revision = '6f6d583caceb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_account_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=12), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('posts', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform in ('facebook','instagram','tiktok')", name='ck_social_account_snapshots_platform'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'captured_on', name='uq_social_account_snapshots_platform_day')
    )
    op.add_column('social_posts', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('social_posts', sa.Column('metrics_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_posts', 'metrics_at')
    op.drop_column('social_posts', 'metrics')
    op.drop_table('social_account_snapshots')
    # ### end Alembic commands ###
