"""integration connections, oauth states, action runs

Revision ID: 6abbbb75fde5
Revises: 94e8251b64e2
Create Date: 2026-09-29 19:47:42.613731
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6abbbb75fde5'
down_revision = '94e8251b64e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connector', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auth_kind', sa.String(length=16), nullable=False),
    sa.Column('key_version', sa.String(length=32), nullable=True),
    sa.Column('secret_blob', sa.LargeBinary(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('account_label', sa.String(length=200), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('connected_by', sa.UUID(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auth_kind in ('oauth','api_key','secret','builtin')", name='ck_integration_connections_auth'),
    sa.CheckConstraint("status in ('connected','error')", name='ck_integration_connections_status'),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'connector', name='uq_integration_connections_connector')
    )
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connector', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('key_version', sa.String(length=32), nullable=False),
    sa.Column('verifier_blob', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('action_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('connector', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('provider_ref', sa.String(length=200), nullable=True),
    sa.Column('provider_call_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('ok','failed','refused')", name='ck_action_runs_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_runs_conversation', 'action_runs', ['conversation_id'], unique=False)
    op.create_index('ix_action_runs_workspace_created', 'action_runs', ['workspace_id', 'created_at'], unique=False)
    op.add_column('bookings', sa.Column('calendar_connector', sa.String(length=40), nullable=True))
    op.add_column('bookings', sa.Column('calendar_event_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'calendar_event_id')
    op.drop_column('bookings', 'calendar_connector')
    op.drop_index('ix_action_runs_workspace_created', table_name='action_runs')
    op.drop_index('ix_action_runs_conversation', table_name='action_runs')
    op.drop_table('action_runs')
    op.drop_table('oauth_states')
    op.drop_table('integration_connections')
    # ### end Alembic commands ###
