"""social media posts

Revision ID: 6f6d583caceb
Revises: b3e8f0a4c6d2
Create Date: 2026-10-07 19:16:14.036511
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6f6d583caceb'
down_revision = 'b3e8f0a4c6d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_credentials',
    sa.Column('platform', sa.String(length=12), nullable=False),
    sa.Column('key_version', sa.String(length=32), nullable=False),
    sa.Column('secret_blob', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('social_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=12), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('group_key', sa.String(length=60), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('generator', sa.String(length=16), nullable=False),
    sa.Column('generator_model', sa.String(length=80), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform in ('facebook','instagram','tiktok')", name='ck_social_posts_platform'),
    sa.CheckConstraint("status in ('draft','scheduled','publishing','published','failed','skipped','cancelled')", name='ck_social_posts_status'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_posts_status_due', 'social_posts', ['status', 'scheduled_for'], unique=False)
    op.create_index('uq_social_posts_platform_slot', 'social_posts', ['platform', 'slot_date'], unique=True, postgresql_where=sa.text("status not in ('cancelled','skipped')"))
    op.create_table('social_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'position', name='uq_social_media_post_position')
    )
    op.create_index(op.f('ix_social_media_post_id'), 'social_media', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_media_post_id'), table_name='social_media')
    op.drop_table('social_media')
    op.drop_index('uq_social_posts_platform_slot', table_name='social_posts', postgresql_where=sa.text("status not in ('cancelled','skipped')"))
    op.drop_index('ix_social_posts_status_due', table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_table('social_credentials')
    # ### end Alembic commands ###
