"""social prospects

Revision ID: 793d6de4d9bb
Revises: 3da6b0abc2dc
Create Date: 2026-10-08 15:34:22.127896
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '793d6de4d9bb'
down_revision = '3da6b0abc2dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_prospects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cvr', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=40), nullable=False),
    sa.Column('industry_text', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('facebook_url', sa.String(length=300), nullable=True),
    sa.Column('instagram_url', sa.String(length=300), nullable=True),
    sa.Column('tiktok_url', sa.String(length=300), nullable=True),
    sa.Column('suggested_comment', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('found_on', sa.Date(), nullable=False),
    sa.Column('acted_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('acted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('new','done','skipped')", name='ck_social_prospects_status'),
    sa.ForeignKeyConstraint(['acted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cvr')
    )
    op.create_index('ix_social_prospects_status_found', 'social_prospects', ['status', 'found_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_prospects_status_found', table_name='social_prospects')
    op.drop_table('social_prospects')
    # ### end Alembic commands ###
