"""demo calls

Revision ID: 94e8251b64e2
Revises: e668ed509035
Create Date: 2026-09-28 18:05:13.135044
"""
from alembic import op
import sqlalchemy as sa


revision = '94e8251b64e2'
down_revision = 'e668ed509035'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('cvr', sa.String(length=8), nullable=True),
    sa.Column('consent_version', sa.String(length=40), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seller_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_call_id', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('web','seller')", name='ck_demo_calls_source'),
    sa.CheckConstraint("status in ('calling','done','no_answer','failed','skipped')", name='ck_demo_calls_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demo_calls_phone_created', 'demo_calls', ['phone', 'created_at'], unique=False)
    op.create_index(op.f('ix_demo_calls_provider_call_id'), 'demo_calls', ['provider_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_calls_provider_call_id'), table_name='demo_calls')
    op.drop_index('ix_demo_calls_phone_created', table_name='demo_calls')
    op.drop_table('demo_calls')
    # ### end Alembic commands ###
