"""voice_library

Revision ID: a8a4f6f5ffaf
Revises: 7769c9d94fe1
Create Date: 2026-09-27 11:43:16.288708
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a8a4f6f5ffaf'
down_revision = '7769c9d94fe1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_rights_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('revision', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('allowed_uses', sa.Text(), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=False),
    sa.Column('commercial_use', sa.Boolean(), nullable=True),
    sa.Column('subprocessors', sa.Text(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('termination', sa.Text(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('document_key', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('code','model','dataset','speaker_agreement')", name='ck_voice_rights_kind'),
    sa.CheckConstraint("status in ('unreviewed','verified','blocked')", name='ck_voice_rights_status'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('dialect', sa.String(length=80), nullable=True),
    sa.Column('dialect_basis', sa.Text(), nullable=False),
    sa.Column('age_description', sa.String(length=80), nullable=True),
    sa.Column('timbre', sa.String(length=120), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=12), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('sample_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(visibility = 'workspace') = (workspace_id is not null)", name='ck_voice_profiles_scope'),
    sa.CheckConstraint("gender in ('female','male','unknown')", name='ck_voice_profiles_gender'),
    sa.CheckConstraint("visibility in ('platform','workspace')", name='ck_voice_profiles_visibility'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('voice_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('characters', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'day', 'kind', name='uq_voice_usage_day')
    )
    op.create_table('voice_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('engine', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('model_repo', sa.String(length=200), nullable=False),
    sa.Column('model_revision', sa.String(length=80), nullable=False),
    sa.Column('checkpoint_key', sa.String(length=300), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rights_record_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("method in ('reference_conditioning','finetuned_checkpoint','trained_from_scratch')", name='ck_voice_versions_method'),
    sa.CheckConstraint("status in ('draft', 'pending_review', 'approved', 'active', 'suspended', 'retired')", name='ck_voice_versions_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'version', name='uq_voice_versions_number')
    )
    op.create_foreign_key('fk_voice_profiles_active_version', 'voice_profiles', 'voice_versions', ['active_version_id'], ['id'],
                          ondelete='SET NULL')
    op.create_table('workspace_voice_settings',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('default_profile_id', sa.UUID(), nullable=True),
    sa.Column('fallback', sa.String(length=16), nullable=False),
    sa.Column('pronunciations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pronunciation_version', sa.Integer(), nullable=False),
    sa.Column('last_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fallback in ('provider_voice','transfer')", name='ck_workspace_voice_fallback'),
    sa.ForeignKeyConstraint(['default_profile_id'], ['voice_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('voice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('provider_call_id', sa.String(length=100), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pronunciations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fallback', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['voice_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_sessions_call', 'voice_sessions', ['provider_call_id'], unique=False)
    op.add_column('campaigns', sa.Column('voice_profile_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_campaigns_voice_profile', 'campaigns', 'voice_profiles', ['voice_profile_id'], ['id'], ondelete='SET NULL')
    op.add_column('phone_numbers', sa.Column('voice_profile_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_phone_numbers_voice_profile', 'phone_numbers', 'voice_profiles', ['voice_profile_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_platform_operator', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_platform_operator')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_phone_numbers_voice_profile', 'phone_numbers', type_='foreignkey')
    op.drop_column('phone_numbers', 'voice_profile_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_campaigns_voice_profile', 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'voice_profile_id')
    op.drop_index('ix_voice_sessions_call', table_name='voice_sessions')
    op.drop_constraint('fk_voice_profiles_active_version', 'voice_profiles', type_='foreignkey')
    op.drop_table('voice_sessions')
    op.drop_table('workspace_voice_settings')
    op.drop_table('voice_versions')
    op.drop_table('voice_usage')
    op.drop_table('voice_profiles')
    op.drop_table('voice_rights_records')
    # ### end Alembic commands ###
