"""standard voice per workspace

Revision ID: bcc6a80d2f06
Revises: 3c1d29602dcc
Create Date: 2026-10-06 18:17:12.072469
"""
from alembic import op
import sqlalchemy as sa


revision = 'bcc6a80d2f06'
down_revision = '3c1d29602dcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_voice_settings', sa.Column('standard_voice', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_voice_settings', 'standard_voice')
    # ### end Alembic commands ###
