"""source import profile suggestion

Revision ID: c9febc48ca3b
Revises: f4681fd5e00d
Create Date: 2026-09-26 09:32:34.004417
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c9febc48ca3b'
down_revision = 'f4681fd5e00d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_imports', sa.Column('profile_suggestion', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_imports', 'profile_suggestion')
    # ### end Alembic commands ###
