"""campaigns

Revision ID: f8c8153ccbb0
Revises: 06fa18c2fcfa
Create Date: 2026-09-26 21:56:46.455654
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f8c8153ccbb0'
down_revision = '06fa18c2fcfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('do_not_call',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'phone', name='uq_do_not_call_phone')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('opening', sa.Text(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('success', sa.Text(), nullable=False),
    sa.Column('phone_number_id', sa.UUID(), nullable=True),
    sa.Column('call_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('call_from', sa.String(length=5), nullable=False),
    sa.Column('call_to', sa.String(length=5), nullable=False),
    sa.Column('package_net_minor', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('max_connected_seconds', sa.Integer(), nullable=False),
    sa.Column('legal_confirmation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('draft','running','paused','completed')", name='ck_campaigns_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_workspace', 'campaigns', ['workspace_id', 'created_at'], unique=False)
    op.create_table('campaign_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('consent_source', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('connected_seconds', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_call_id', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('charged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('charged_net_minor', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('business','consumer')", name='ck_campaign_contacts_kind'),
    sa.CheckConstraint("status in ('pending','calling','done','no_answer','failed','opted_out','skipped')", name='ck_campaign_contacts_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'phone', name='uq_campaign_contacts_phone')
    )
    op.create_index('ix_campaign_contacts_due', 'campaign_contacts', ['campaign_id', 'status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_provider_call_id'), 'campaign_contacts', ['provider_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_contacts_provider_call_id'), table_name='campaign_contacts')
    op.drop_index('ix_campaign_contacts_due', table_name='campaign_contacts')
    op.drop_table('campaign_contacts')
    op.drop_index('ix_campaigns_workspace', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('do_not_call')
    # ### end Alembic commands ###
